# Generated by Django 5.1.6 on 2025-02-23 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
